package gr.aueb.cf.ffa.mapper;

import gr.aueb.cf.ffa.dto.ExpenseRequestDTO;
import gr.aueb.cf.ffa.dto.ExpenseResponseDTO;
import gr.aueb.cf.ffa.model.Expense;
import org.springframework.stereotype.Component;

/**
 * Mapper for converting between Expense entities and DTOs.
 */
@Component
public class ExpenseMapper {

    /**
     * Converts an ExpenseRequestDTO to an Expense entity.
     *
     * @param dto    The ExpenseRequestDTO containing the request data.
     * @param userId The ID of the user creating the expense.
     * @return The mapped Expense entity.
     */
    public Expense toEntity(ExpenseRequestDTO dto, String userId) {
        return new Expense(
                null, // ID will be generated by the database
                userId,
                dto.getType(),
                dto.getAmount(),
                dto.getDate(),
                dto.getNotes()
        );
    }

    /**
     * Converts an Expense entity to an ExpenseResponseDTO.
     *
     * @param expense The Expense entity.
     * @return The mapped ExpenseResponseDTO.
     */
    public ExpenseResponseDTO toResponseDTO(Expense expense) {
        return new ExpenseResponseDTO(
                expense.getId(),
                expense.getUserId(),
                expense.getType(),
                expense.getAmount(),
                expense.getDate(),
                expense.getNotes()
        );
    }
}
