package gr.aueb.cf.ffa.model;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Document(collection = "users") // Specifies the MongoDB collection
    public class User {
        @Id
        private String id; // Unique identifier (automatically generated by MongoDB)
        private String username; // Unique username for login
        private String password; // Hashed password for authentication
        private String email; // User's email address
        private String role; // Role-based access (e.g., "USER")
    }


