package gr.aueb.cf.ffa.model;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;

/**
 * Represents an expense entry associated with a user.
 * Stored in the "expenses" collection in MongoDB.
 */
@Document(collection = "expenses")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "Model representing an expense entry associated with a user.")
public class Expense {

    @Id
    @Schema(
            description = "Unique identifier for the expense entry (automatically generated by MongoDB).",
            example = "64b7cfe2c3d2a12345678901",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private String id;

    @Schema(
            description = "The ID of the user associated with this expense entry.",
            example = "user123",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private String userId;

    @Schema(
            description = "The type of expense (e.g., 'Rent', 'Utilities', 'Groceries').",
            example = "Rent"
    )
    private String type;

    @Schema(
            description = "The amount of the expense. Must be a positive number.",
            example = "500.75"
    )
    private double amount;

    @Schema(
            description = "The date when the expense was incurred.",
            example = "2025-01-10"
    )
    private LocalDate date;

    @Schema(
            description = "Optional notes or comments for the expense entry.",
            example = "January rent payment."
    )
    private String notes;
}
