package gr.aueb.cf.ffa.model;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;

/**
 * Represents an income entry associated with a user.
 * Stored in the "incomes" collection in MongoDB.
 */
@Document(collection = "incomes")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "Model representing an income entry associated with a user.")
public class Income {

    @Id
    @Schema(
            description = "Unique identifier for the income entry (automatically generated by MongoDB).",
            example = "64b7cfe2c3d2a12345678901",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private String id;

    @Schema(
            description = "The ID of the user associated with this income entry.",
            example = "user123",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private String userId;

    @Schema(
            description = "The type of income (e.g., 'Gross Pay', 'Net Pay', 'Tips').",
            example = "Gross Pay"
    )
    private String type;

    @Schema(
            description = "The amount of income. Must be a positive number.",
            example = "1500.50"
    )
    private double amount;

    @Schema(
            description = "The date when the income was received.",
            example = "2025-01-01"
    )
    private LocalDate date;

    @Schema(
            description = "Optional notes or comments for the income entry.",
            example = "Monthly salary for January."
    )
    private String notes;
}
