package gr.aueb.cf.ffa.model;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

    @Getter
    @Setter
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Document(collection = "users") // Specifies the MongoDB collection
    public class User {
        @Id
        private String id; // Unique identifier (automatically generated by MongoDB)

        @Pattern(
                regexp = "^[a-zA-Z0-9_]{5,20}$",
                message = "Username must be 5-20 characters, alphanumeric, and can include underscores."
        )
        private String username;


        @Pattern(
                regexp = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
                message = "Password must be at least 8 characters, include 1 uppercase, 1 lowercase, 1 number, and 1 special character."
        )
        private String password;


        @Pattern(
                regexp = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$\n",
                message = "Invalid email format."
        )
        private String email;


        private String role; // Role-based access (e.g., "USER")
    }


